---
- hosts: all
  become: true
  tasks:

  - name: install python3
    apt:
      name: python3

  - name: install pip3
    apt:
      name: python3-pip

#  - name: use pip3 as default pip
#    apt:
#      name: 

#  - name: use python3 as default python
#    apt:
#      name: 

  - name: install Java open-jdk
    apt:
      name: openjdk-11-jdk 

  - name: install MariaDB
    apt:
      name: mariadb-server
